name: Repository Dispatch
on:
 push:
  branches: [ main ]
    
jobs:
  build:
   name: trigger
   runs-on: ubuntu-latest
   steps:
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: ${{ github.repository_owner }}
          repo: test-automation
          ref: ${{ github.event.repository.default_branch || 'main' }}
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow_file_name: main.yml
          trigger_workflow: true
          wait_workflow: true
          propagate_failure: true
