name: Repository Dispatch
on:
  pull_request:
   branches: [ main ]
  
jobs:
  build:
   name: Repository Dispatch
   runs-on: ubuntu-latest
   steps:
      - name: Fetching pull request number
        shell: bash
        run: |
          echo github.event.number = ${{ github.event.number  }}
          echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
          echo ${{ github.event.pull_request.number }} > prId.txt

      
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: wellsterhealthtech/test-automation
          event-type: my-event
          client-payload: '{"prId": "${{ github.event.pull_request.number }}"}'
          wait_workflow: true
          
